name: Publish Android
description: Get a release by tag, latest or current release
author: Giao Ho
inputs:
  serviceAccountJson:
    description: The service account json private key file or the raw json text of the service account private key to authorize the upload request
    required: true
  packageName:
    description: The package name, or Application Id, of the app you are uploading
    required: true
  releaseFile:
    description: The Android release file to upload (.apk or .aab). Multiple files can be supplied on new lines. Supports glob
    required: true
  releaseName:
    description: The name of this release. If not set it's generated automatically from the APKs versionName. Default is configured by Google Play Console
    required: false
  track:
    description: The track in which you want to assign the uploaded app.
    default: production
    required: true
  inAppUpdatePriority:
    description: In-app update priority of the release. All newly added APKs in the release will be considered at this priority. Can take values in the range [0, 5], with 5 the highest priority.
    default: '0'
    required: false
  userFraction:
    description: Portion of users who should get the staged version of the app. Accepts values between 0.0 and 1.0 (exclusive-exclusive).
    required: false
  status:
    description: Release status. This can be set to 'draft' to complete the release at some other time.
    required: false
    # Options: `draft`, `inProgress`, `halted`, `completed`
    default: completed
  whatsNewDirectory:
    description: The directory of localized "whats new" files to upload as the release notes. The files contained in the whatsNewDirectory MUST use the pattern whatsnew-<LOCALE> where LOCALE is using the BCP 47 format
    required: false
  mappingFile:
    description: The mapping.txt file used to de-obfuscate your stack traces from crash reports
    required: false
  debugSymbols:
    description: The native-debug-symbols.zip file or folder that contains your debug symbols
    required: false
  changesNotSentForReview:
    description: Indicates that the changes in this edit will not be reviewed until they are explicitly sent for review from the Google Play Console
    default: 'false'
    required: false
  existingEditId:
    description: The ID of an existing edit that has not been completed. If this is supplied, the action will append information to that rather than creating an edit
    required: false
outputs:
  internalSharingDownloadUrl:
    # Environment Variable: INTERNAL_SHARING_DOWNLOAD_URL
    description: A JSON list containing the download urls for every release file uploaded using the `internalsharing` track
  internalSharingDownloadUrls:
    # Environment Variable: INTERNAL_SHARING_DOWNLOAD_URLS
    description: The download url for the last release file uploaded using the `internalsharing` track
runs:
  using: node16
  main: action/index.js
branding:
  icon: smartphone
  color: green
